const random = [
  "Against the Wall",
  "Aguirre, Wrath of God",
  "Akira",
  "Aladdin",
  "Alan Partridge Alpha Papa",
  "Alice in Wonderland",
  "Alien (Series)",
  "Alita Battle Angel",
  "All About Eve",
  "All Cheerleaders Die",
  "All the Boys Love Mandy Lane",
  "All the Colors of the Dark",
  "Alphaville",
  "Altered States",
  "Amadeus",
  "Amazon Women on the Moon",
  "Autopsy of Jane Doe, The",
  "Avatar",
  "Babadook, The",
  "Baby Blood",
  "Back to Black: The V/H/S Horror Franchise and the Thrill of a Mystery Tape",
  "Bad Batch, The",
  "Bad Biology",
  "Bad Boys",
  "Bad Education",
  "Bad Girls Go to Hell",
  "Bad Grandpa",
  "Bad Lieutenant",
  "Bad Santa",
  "Baise-moi",
  "Beasts of the Southern Wild",
  "Bedazzled",
  "Beetlejuice",
  "Behind the Curve",
  "Behind the Mask",
  "Being John Malkovich",
  "Belladonna of Sadness",
  "Belle de Jour",
  "Bellflower",
  "Berberian Sound Studio",
  "Better Watch Out",
  "Betting on Zero",
  "Beyond the Valley of the Dolls",
  "Bicentennial Man",
  "Color Out of Space",
  "Colossal",
  "Colossus: The Forbin Project",
  "Company Men, The",
  "Compliance",
  "Computer Chess",
  "Conan the Barbarian",
  "Confessions of a Dangerous Mind",
  "Constantine",
  "Contact",
  "Contagion",
  "Cooties",
  "Cop Car",
  "Coraline",
  "Corpse Bride",
];
