const random = [
  "Against the Wall",
  "Aguirre, Wrath of God",
  "Akira",
  "Aladdin",
  "Alan Partridge Alpha Papa",
  "Alice in Wonderland",
  "Alien (Series)",
  "Alita Battle Angel",
  "All About Eve",
  "All Cheerleaders Die",
  "All the Boys Love Mandy Lane",
  "All the Colors of the Dark",
  "Alphaville",
  "Altered States",
  "Amadeus",
  "Amazon Women on the Moon",
  "Autopsy of Jane Doe, The",
  "Avatar",
  "Babadook, The",
  "Baby Blood",
  "Back to Black: The V/H/S Horror Franchise and the Thrill of a Mystery Tape",
  "Bad Batch, The",
  "Bad Biology",
  "Bad Boys",
  "Bad Education",
  "Bad Girls Go to Hell",
  "Bad Grandpa",
  "Bad Lieutenant",
  "Bad Santa",
  "Baise-moi",
  "Beasts of the Southern Wild",
  "Bedazzled",
  "Beetlejuice",
  "Behind the Curve",
  "Behind the Mask",
  "Being John Malkovich",
  "Belladonna of Sadness",
  "Belle de Jour",
  "Bellflower",
  "Berberian Sound Studio",
  "Better Watch Out",
  "Betting on Zero",
  "Beyond the Valley of the Dolls",
  "Bicentennial Man",
  "Color Out of Space",
  "Colossal",
  "Colossus: The Forbin Project",
  "Company Men, The",
  "Compliance",
  "Computer Chess",
  "Conan the Barbarian",
  "Confessions of a Dangerous Mind",
  "Constantine",
  "Contact",
  "Contagion",
  "Cooties",
  "Cop Car",
  "Coraline",
  "Corpse Bride",
  "Chasing Amy",
  "Chelsea Girls",
  "Child's Play (Chucky Series)",
  "Children of Men",
  "Children of the Corn (Series)",
  "Chillerama",
  "Chinatown",
  "Chopping Mall",
  "Christine",
  "Christmas on Mars",
  "Chronicle",
  "Chungking Express",
  "Citizen Kane",
  "Citizenfour",
  "City of the Living Dead",
  "Class of 1984",
  "Class of 1999",
  "Clear and Present Danger",
  "Clerks",
  "Climax",
  "Clockers",
  "Closer",
  "Cloud Atlas",
  "Cloverfield",
  "Clown",
  "Clue",
  "Cockfighter",
  "Coffy",
  "Coherence",
  "Cold Fish",
  "Cold Souls",
  "Cold in July",
  "Collateral",
  "Contact",
  "Contagion",
  "Cooties",
  "Coraline",
  "Corpse Bride",
  "Cosmopolis",
  "Crank",
  "Dancer in the Dark",
  "Deer Hunter, The",
  "Deerskin",
  "Delicatessen",
  "Deliver Us From Evil",
  "Deliverance",
  "Dementia 13",
  "Demolition Man",
  "Demon Seed",
  "Demonlover",
  "Desperado",
  "Desperate Living",
  "Destroyer",
  "Detroit Rock City",
  "Die Hard",
  "Dig!",
  "Digging Up the Marrow",
  "Director's Cut",
  "Dirty Work",
  "Django",
  "Django Unchained",
  "Do the Right Thing",
  "Dog Day Afternoon",
  "Dog Soldiers",
  "Dogs Don't Wear Pants",
  "Dogtooth",
  "Dogville",
  "Equilibrium",
  "Eraserhead",
  "Escape from LA",
  "Escape from NY",
  "Escape from Tomorrow",
  "Eternal Sunshine of the Spotless Mind",
  "Even Dwarfs Started Small",
  "Everly",
  "Everybody Wants Some",
  "Excision",
  "Exit Through the Gift Shop",
  "Forrest Gump",
  "Four Flies on Grey Velvet",
  "Four Rooms",
  "Foxy Brown",
  "Frailty",
  "Frances Ha",
  "Frankenstein",
  "Freaks",
  "Freddy vs Jason",
  "Freeway",
  "Friday",
  "Godfather",
  "Godzilla: Final Wars",
  "Gojira",
  "Gold Diggers of 1933",
  "Goldeneye",
  "Gone Girl",
  "Gone with the Wind",
  "Good Neighbor",
  "Good Night and Good Luck",
  "Good Time",
  "Good, the Bad and the Ugly",
  "Gothic",
  "Haunted World of El Superbeasto, The",
  "Hausu",
  "Haywire",
  "He Died with a Felafel in His Hand",
  "He Got Game",
  "Head",
  "Heartbeeps",
  "Hearts and Minds",
  "Heat",
  "Inside",
  "Inside Llewyn Davis",
  "Insidious",
  "Insomnia",
  "Intacto",
  "Jodorowsky's Dune",
  "Joe",
  "John Carpenter's Vampires",
  "John Dies at the End",
  "John Wick",
  "Jonestown",
  "Joy Ride",
  "Kindergarten Cop",
  "King of New York",
  "Kinky Boots",
  "Kiss Kiss, Bang Bang",
  "Klown",
  "Klute",
  "Looney Tunes: Back in Action",
  "Looper",
  "Loose Change",
  "Lord of War",
  "Lost Highway",
  "Lost in Translation",
  "Love",
  "Manhattan",
  "Manhattan Murder Mystery",
  "Manhunter",
  "Maniac",
  "Maniac Cop (Series)",
  "Mank",
  "Maps to the Stars",
  "Marihuana",
];
